apiVersion: v1
kind: Service
metadata:
  name: todo-frontend
  namespace: todo
spec:
  type: {{ .Values.service.type }}
  selector:
    app: todo-frontend
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
